[E 2024-03-23 17:03:32,860 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2024-03-23 17:04:06,425 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2024-03-23 17:05:47,154 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': "Token doesn't have production permission.", 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-03-23 17:06:07,896 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': "Token doesn't have production permission.", 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-03-23 17:10:20,719 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': "Token doesn't have production permission.", 'ip_address': '118.150.47.40', 'person_id': 'F129970274', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2024-03-24 17:31:01,902 /opt/homebrew/anaconda3/lib/python3.11/site-packages/shioaji/utils.py:49:raise_resp_error] {'status': {'status_code': 422}, 'response': {'detail': [{'loc': ['body', 'scanner_input', 'date'], 'msg': 'invalid date format', 'type': 'value_error.date'}]}}
